### PR TITLE
Newer csproj format and target .NET Standard

### LINKED ISSUE #13: .NET Core support
Hangfire.SimpleInjector doesn't seem to work in a project using ASP.NET Core; both Hangfire and SimpleInjector seem to work fine so this is likely just a matter of recompiling it as a .NET Core project. Shared projects could perhaps be used to avoid duplication of code.

### PR DESCRIPTION
**Pull request by JanVargovsky**
Fixes #13 

Solution and csproj(s) were converted to newer csproj format - thanks [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017) tool.

I've removed a bunch of files that are not necessary, including scripts for generating a nuget package. This was replaced with simple  `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`, I've updated the package information too.

I hope all you need is to build the release version and [publish the package](https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package).

### CODE REVIEW

**Comment by devmondo** [comment]
thank you very much!!!

**Comment by JanVargovsky** [comment]
Will you publish the 1.3.2 version or do you need some help?

**Comment by devmondo** [comment]
i dont do NET anymore so if you can take a snap at it i would appreciate it :)

**Comment by JanVargovsky** [comment]
Here is the file [Hangfire.SimpleInjector.1.3.2.zip](https://github.com/devmondo/HangFire.SimpleInjector/files/5807465/Hangfire.SimpleInjector.1.3.2.zip)

you need to unzip it and upload either [manually](https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package#web-portal-use-the-upload-package-tab-on-nugetorg) or via CLI but you need an API key for the account. Do you still have the account here?

Btw, since you are not in .NET world anymore, we might talk about transferring/adding the ownership to somebody else.

**Comment by devmondo** [comment]
done many many thanks :)
https://www.nuget.org/packages/HangFire.SimpleInjector/1.3.2

**Pull request merged**
